### ISSUE TITLE
Navigating to a previously loaded story results in an error

### ISSUE THREAD

**Issue by ianbusko** [ianbusko/the-noted-project#10]
Navigate to any story.
Scroll down any number of slides.
Return to home screen.
Navigate to previous story. Notice that page fails with lots of error messages revolving around withScrollSnapping.js

**Comment by ianbusko** [comment]
@peterhershey, can you replicate this issue? I'm not seeing it currently.

**Comment by peterhershey** [comment]
@ianbusko I believe the issue is that it tries to "remember" your spot in the story for later. example scenario:

1. navigate to Deepunu's story. Scroll to slide 5
2. use the navbar to go to the home page
3. navigate back to Deepunu's story, and you start on slide 5.
4. But then, the site tries to course correct, so when you scroll to the next slide, the scrolling freaks out and takes you to slide 2.

make sense? ideally whenever you navigate to a story you will start on slide 1. It should never "remember" your previous scroll position.

**Comment by peterhershey** [comment]
oh ok. well, then I don't know. I've never had the issue that you described when you opened the issue
